name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: composer run-script phpunit tests

    - name: Run linter
      run: composer run-script phpcs -- --standard=PSR12 src tests

#    - name: Test & publish code coverage
#      uses: actions/checkout@v2
#      env:
#        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
#      with:
#        debug: true

    # Publish code coverage on Code Climate
    # https://github.com/paambaati/codeclimate-action
    - name: Run test & publish code coverage
      #uses: paambaati/codeclimate-action@v2.4.0
      run: |
          export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter format-coverage -t lcov coverage/lcov.info
          ./cc-test-reporter upload-coverage
      # Add Code Climate secret key
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: make test
        debug: true
